#!/bin/sh

UJA="update-java-alternatives"
ENV_PATH_HEADER="#JAVA HOME PATH Imotor"
COMMENT_PATH="#JAVA_HOME_COMMENT"
ALIAS_BASH=~/.bashrc

if uname -a | grep x86_64 >/dev/null ; then
    ARCH_SUFFIX=amd64
else
    ARCH_SUFFIX=i386
fi

# UJA is for update-java-alternatives
if [[ -d "/usr/lib/jvm/java-6-openjdk-$ARCH_SUFFIX" ]] ; then
    OPENJDK6_UJA_ALIAS="java-1.6.0-openjdk-$ARCH_SUFFIX"
    OPENJDK6_JAVA_HOME="/usr/lib/jvm/java-6-openjdk-$ARCH_SUFFIX"
else
    OPENJDK6_UJA_ALIAS="java-1.6.0-openjdk"
    OPENJDK6_JAVA_HOME="/usr/lib/jvm/java-6-openjdk"
fi

if [[ -d "/usr/lib/jvm/java-7-openjdk-$ARCH_SUFFIX" ]] ; then
    OPENJDK7_UJA_ALIAS="java-1.7.0-openjdk-$ARCH_SUFFIX"
    OPENJDK7_JAVA_HOME="/usr/lib/jvm/java-7-openjdk-$ARCH_SUFFIX"
else
    OPENJDK7_UJA_ALIAS="java-1.7.0-openjdk"
    OPENJDK7_JAVA_HOME="/usr/lib/jvm/java-7-openjdk"
fi

if [[ -d "/usr/lib/jvm/java-8-openjdk-$ARCH_SUFFIX" ]] ; then
    OPENJDK8_UJA_ALIAS="java-1.8.0-openjdk-$ARCH_SUFFIX"
    OPENJDK8_JAVA_HOME="/usr/lib/jvm/java-8-openjdk-$ARCH_SUFFIX"
else
    OPENJDK8_UJA_ALIAS="java-1.8.0-openjdk"
    OPENJDK8_JAVA_HOME="/usr/lib/jvm/java-8-openjdk"
fi

# The java::oraclejdk7 recipe from github.com/travis-ci/travis-cookbooks
# takes care of this alias. We take it for granted here. MK.
if [[ -d "/usr/lib/jvm/java-6-oracle-$ARCH_SUFFIX" ]] ; then
    ORACLEJDK6_UJA_ALIAS="java-6-oracle-$ARCH_SUFFIX"
    ORACLEJDK6_JAVA_HOME="/usr/lib/jvm/java-6-oracle-$ARCH_SUFFIX"
else
    ORACLEJDK6_UJA_ALIAS="java-6-oracle"
    ORACLEJDK6_JAVA_HOME="/usr/lib/jvm/java-6-oracle"
fi

if [[ -d "/usr/lib/jvm/java-7-oracle-$ARCH_SUFFIX" ]] ; then
    ORACLEJDK7_UJA_ALIAS="java-7-oracle-$ARCH_SUFFIX"
    ORACLEJDK7_JAVA_HOME="/usr/lib/jvm/java-7-oracle-$ARCH_SUFFIX"
else
    ORACLEJDK7_UJA_ALIAS="java-7-oracle"
    ORACLEJDK7_JAVA_HOME="/usr/lib/jvm/java-7-oracle"
fi

# The java::oraclejdk8 recipe from github.com/travis-ci/travis-cookbooks
# takes care of this alias. We take it for granted here. MK.
if [[ -d "/usr/lib/jvm/java-8-oracle-$ARCH_SUFFIX" ]] ; then
    ORACLEJDK8_UJA_ALIAS="java-8-oracle-$ARCH_SUFFIX"
    ORACLEJDK8_JAVA_HOME="/usr/lib/jvm/java-8-oracle-$ARCH_SUFFIX"
else
    ORACLEJDK8_UJA_ALIAS="java-8-oracle"
    ORACLEJDK8_JAVA_HOME="/usr/lib/jvm/java-8-oracle"
fi

switch_to_openjdk6 () {
    echo "Switching to OpenJDK6 ($OPENJDK6_UJA_ALIAS), JAVA_HOME will be set to $OPENJDK6_JAVA_HOME"
    sudo $UJA --set "$OPENJDK6_UJA_ALIAS"
    ENV_PATH="JAVA_HOME=$OPENJDK6_JAVA_HOME"
    set_env_bashrc "$ENV_PATH_HEADER" "$ENV_PATH" "$COMMENT_PATH"
}

switch_to_openjdk7 () {
    echo "Switching to OpenJDK7 ($OPENJDK7_UJA_ALIAS), JAVA_HOME will be set to $OPENJDK7_JAVA_HOME"
    sudo $UJA --set "$OPENJDK7_UJA_ALIAS"
    ENV_PATH="JAVA_HOME=$OPENJDK7_JAVA_HOME"
    set_env_bashrc "$ENV_PATH_HEADER" "$ENV_PATH" "$COMMENT_PATH"
}

switch_to_openjdk8 () {
    echo "Switching to OpenJDK8 ($OPENJDK8_UJA_ALIAS), JAVA_HOME will be set to $OPENJDK8_JAVA_HOME"
    sudo $UJA --set "$OPENJDK8_UJA_ALIAS"
    ENV_PATH="JAVA_HOME=$OPENJDK8_JAVA_HOME"
    set_env_bashrc "$ENV_PATH_HEADER" "$ENV_PATH" "$COMMENT_PATH"
}

switch_to_oraclejdk6 () {
    echo "Switching to Oracle JDK6 ($ORACLEJDK6_UJA_ALIAS), JAVA_HOME will be set to $ORACLEJDK6_JAVA_HOME"
    sudo $UJA --set "$ORACLEJDK6_UJA_ALIAS"
    ENV_PATH="JAVA_HOME=$ORACLEJDK6_JAVA_HOME"
    set_env_bashrc "$ENV_PATH_HEADER" "$ENV_PATH" "$COMMENT_PATH"
}

switch_to_oraclejdk7 () {
    echo "Switching to Oracle JDK7 ($ORACLEJDK7_UJA_ALIAS), JAVA_HOME will be set to $ORACLEJDK7_JAVA_HOME"
    sudo $UJA --set "$ORACLEJDK7_UJA_ALIAS"
    ENV_PATH="JAVA_HOME=$ORACLEJDK7_JAVA_HOME"
    set_env_bashrc "$ENV_PATH_HEADER" "$ENV_PATH" "$COMMENT_PATH"
}

switch_to_oraclejdk8 () {
    echo "Switching to Oracle JDK8 ($ORACLEJDK8_UJA_ALIAS), JAVA_HOME will be set to $ORACLEJDK8_JAVA_HOME"
    sudo $UJA --set "$ORACLEJDK8_UJA_ALIAS"
    ENV_PATH="JAVA_HOME=$ORACLEJDK8_JAVA_HOME"
    set_env_bashrc "$ENV_PATH_HEADER" "$ENV_PATH" "$COMMENT_PATH"
}

print_path_of_openjdk6 () {
    echo "$OPENJDK6_JAVA_HOME"
}

print_path_of_openjdk7 () {
    echo "$OPENJDK7_JAVA_HOME"
}

print_path_of_openjdk8 () {
    echo "$OPENJDK8_JAVA_HOME"
}

print_path_of_oraclejdk7 () {
    echo "$ORACLEJDK7_JAVA_HOME"
}

print_path_of_oraclejdk8 () {
    echo "$ORACLEJDK8_JAVA_HOME"
}

warn_jdk_not_known () {
    echo "Sorry, but JDK '$1' is not known." >&2
}

switch_jdk()
{
    case "${1:-default}" in
        openjdk6|openjdk1.6|openjdk1.6.0|jdk6|1.6.0|1.6|6.0)
            switch_to_openjdk6
            ;;
        openjdk7|jdk7|1.7.0|1.7|7.0)
            switch_to_openjdk7
            ;;
        openjdk8|jdk8|1.8.0|1.8|8.0)
            switch_to_openjdk8
            ;;
        oraclejdk6|oraclejdk1.6|oraclejdk1.6.0|oracle6|oracle1.6.0|oracle6.0|oracle|sunjdk6|sun6|sun)
            switch_to_oraclejdk6
            ;;
        oraclejdk7|oraclejdk1.7|oraclejdk1.7.0|oracle7|oracle1.7.0|oracle7.0|oracle|sunjdk7|sun7|sun)
            switch_to_oraclejdk7
            ;;
        oraclejdk8|oraclejdk1.8|oraclejdk1.8.0|oracle8|oracle1.8.0|oracle8.0)
            switch_to_oraclejdk8
            ;;
        default)
            switch_to_oraclejdk7
            ;;
        *)
            warn_jdk_not_known "$1"
            false
            ;;
    esac
}


print_java_path()
{
    typeset JDK
    JDK="$1"

    case "$JDK" in
        openjdk6|openjdk1.6|openjdk1.6.0|jdk6|1.6.0|1.6|6.0)
            print_path_of_openjdk6
            ;;
        openjdk7|jdk7|1.7.0|1.7|7.0)
            print_path_of_openjdk7
            ;;
        openjdk8|jdk8|1.8.0|1.8|8.0)
            print_path_of_openjdk8
            ;;	    
        oraclejdk7|oraclejdk1.7|oraclejdk1.7.0|oracle7|oracle1.7.0|oracle7.0|oracle|sunjdk7|sun7|sun)
            print_path_of_oraclejdk7
            ;;
        oraclejdk8|oraclejdk1.8|oraclejdk1.8.0|oracle8|oracle1.8.0|oracle8.0)
            print_path_of_oraclejdk8
            ;;
        default)
            print_path_of_openjdk7
            ;;
        *)
            warn_jdk_not_known "$JDK"
            ;;
    esac
}


jdk_switcher()
{
    typeset COMMAND JDK
    COMMAND="$1"
    JDK="$2"

    case "$COMMAND" in
        -s)
            switch_jdk "$JDK"
            ;;
        -p)
            print_java_path "$JDK"
            ;;
        *)
            usage
            false
            ;;
    esac

    return $?
}

usage() {
    echo -e "Usage: jdk_switcher {-s|-p} [ JDK version ]

OPTIONS
       -s,
           switch the jdk version
               jdk_switcher -s openjdk6
               jdk_switcher -s oraclejdk8
       -p,
           print the jdk path
               jdk_switcher -p openjdk6
               jdk_switcher -p oraclejdk8
            " >&2
}

clean_bashrc() {
  if grep -q "$1" "$ALIAS_BASH"; then
      sed -i '/'"$1"'/d' $ALIAS_BASH
  fi
  #if grep -q "$2" "$ALIAS_BASH"; then
  #  sed -i '/'"$2"'/d' $ALIAS_BASH
  #fi
}

set_env_bashrc() {
    if [ -f ~/.bashrc ]; then
        clean_bashrc $1 $2
    fi
    sleep 2
    echo $1>> ~/.bashrc &&
    echo $2 $3>> ~/.bashrc
}

jdk_switcher $1 $2
