#gitolite@192.168.1.152:daily.git            //dailybuild仓库
#gitolite@192.168.1.152:gitolite-admin.git   //gitolite配置仓库

gitolite@192.168.1.152:imotor/doc/dm.git        //研发部文档
gitolite@192.168.1.152:imotor/doc/platform.git  //平台相关文档
gitolite@192.168.1.152:imotor/doc/project.git   //项目相关文档
gitolite@192.168.1.152:imotor/doc/mcu.git       //mcu文档
#gitolite@192.168.1.152:imotor/doc/dqa.git       //dqa相关文档 
#gitolite@192.168.1.152:imotor/doc/can.git       //Can协议相关文档

gitolite@192.168.1.152:imotor/tools/AndroidCfgEdit.git  //配置工具仓库
gitolite@192.168.1.152:imotor/tools/build_scripts.git   //编译脚本工具仓库
gitolite@192.168.1.152:imotor/tools/build_tools.git     //编译工具仓库
gitolite@192.168.1.152:imotor/tools/android_strings.git //字符串整理替换工具
